apiVersion: v1
kind: Pod
metadata:
  name: ngrok-tunnel
  labels:
    app: ngrok  
spec:
  containers:
  - name: ngrok
    image: docker.io/renaneustaquio/ngrok-image
    command:
      - "/bin/sh"
      - "-c"
      - |
        /usr/local/bin/ngrok config add-authtoken $(NGROK_AUTHTOKEN) && \
        /usr/local/bin/ngrok http --region=us --log=stdout --hostname=jolly-sure-cardinal.ngrok-free.app mckingapi-service:80
    env:
      - name: NGROK_AUTHTOKEN
        valueFrom:
          secretKeyRef:
            name: ngrok-secrets
            key: authtoken