apiVersion: v1
kind: Service
metadata:
  name: mckingapi-service
  labels:
    run: mckingapi-service
spec:
  selector:
    app: mckingapi-pod
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: NodePort
