name: Deploy-EKS
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy-EKS
    runs-on: ubuntu-latest
    needs: Publica_Image
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Setup kubeconfig EKS
        run: aws eks update-kubeconfig --name mcking-cluster --region us-east-1

      - name: Deployment no EKS
        run: |
          kubectl rollout restart deployment/mckingapi-deployment --namespace=default

      - name: Verificar rollout do deploy
        run: kubectl rollout status deployment/mckingapi-deployment --namespace=default