name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build da imagem Docker
        run: |
          docker buildx build -t ghcr.io/renaneustaquio/mckingapi:latest -f ./API/Dockerfile .

      - name: Push da imagem Docker
        run: |
          docker push ghcr.io/${{ github.actor }}/mckingapi:latest
      
      - name: Torna a imagem publica
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"visibility": "public"}' \
            https://api.github.com/user/packages/container/${{ github.repository }}/ghcr.io/${{ github.repository }}/mckingapi/versions/latest