name: Publica_Image
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Publica_Image
    runs-on: ubuntu-latest
    needs: SonarQube
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore, Build e Publish
        run: |
          dotnet restore 9soat-g63-mc-king.sln
          dotnet build --configuration Release 9soat-g63-mc-king.sln
          dotnet publish --configuration Release -o ./publish 9soat-g63-mc-king.sln

      - name: Docker Login - GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/mckingapi:latest -f ./API/Dockerfile .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.actor }}/mckingapi:latest

      - name: Make GHCR Image Public
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"visibility": "public"}' \
            https://api.github.com/user/packages/container/${{ github.repository }}/ghcr.io/${{ github.repository }}/mckingapi/versions/latest